dependencies:
  - scipy==1.6.1
  - seaborn==0.11.0
  - networkx==2.5
  - python_docx==0.8.11
  - pandas==1.5.3
  - docxtpl==0.16.6
  - openpyxl==3.1.2
  - matplotlib==3.3.2
  - numpy==1.24.2
  - watermark==2.1.0
  - docx==0.2.4
  - Pillow==9.5.0
  - scikit_learn==1.2.2
